name: space
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.3.3
  giffy_dialog: ^1.3.0
  dropdown_formfield: ^0.1.0
  flutter_screenutil: ^0.6.0
  carousel_slider: ^1.3.0
  feather_icons_flutter: ^4.7.4
  flutter_slidable: ^0.5.3
  font_awesome_flutter: ^8.5.0
  line_icons: ^0.2.0
  http: ^0.12.0+2
  provider: ^3.0.0
  intl: ^0.15.8
  material_design_icons_flutter: ^3.2.4096
  outline_material_icons: ^0.1.0
  flutter_money_formatter: ^0.8.3
  morpheus: ^1.2.2+1
  location: ^2.3.5
  shared_preferences: ^0.5.3
  flutter_markdown: ^0.2.0
  parse_server_sdk: ^1.0.24
  sqflite: ^1.1.6+3
  flutter_bloc: ^0.20.1
  equatable: ^0.4.0
  meta: ^1.1.6
  dio: ^2.1.0
  mask_shifter: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
  - assets/logo.png
  - assets/space_demo.flr
  - assets/job.png
  - assets/job2.png
  - assets/mekuru.png
  - assets/blog.png
  - assets/home.png
  - assets/img_profil.png
  - assets/img_profil_2.png
  - assets/img_profil_3.png
  - assets/img_profil_4.png
  - assets/recent_job.png
  - assets/nav_astro.png
  - assets/mekuru_2.png
  - assets/ketapang.png
  - assets/background-1.png
  - assets/vector-1.png
  - assets/vector-2.png
  - assets/img_profile-1.png
  - assets/img_profile-2.png
  - assets/logo_vertical.png
  - assets/vector-3.png
  - assets/ellipse_1.png
  - assets/ellipse_2.png
  - assets/icon1.png
  - assets/icon2.png
  - assets/icon3.png
  - assets/icon4.png
  - assets/icon5.png
  - assets/icon6.png
  - assets/icon7.png
  - assets/icon8.png
  - assets/icon9.png
  - assets/icon10.png
  - assets/icon11.png
  - assets/icon12.png
  - assets/icon13.png
  - assets/icon14.png
  - assets/icon15.png
  - assets/icon16.png
  - assets/vector-4.png
  - assets/vector-5.png
  - assets/vector-6.png
  - assets/vector-7.png
  - assets/vector-8.png
  - assets/vector-9.png
  - assets/vector-10.png
  - assets/vector-11.png
  - assets/vector-12.png
  - assets/vector-13.png
  - assets/vector-14.png
  - assets/vector-15.png
  - assets/vector-16.png
  - assets/grunge.png
  - assets/background-2.png
  - assets/up2u.png
  - assets/logo-hitam.png
  - assets/gmail.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: VarelaRound
      fonts:
        - asset: fonts/VarelaRound.ttf
    - family: Quicksand-Regular
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-SemiBold.ttf
    - family: Cocogoose
      fonts:
        - asset: fonts/Cocogoose.ttf
    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
